config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :lessons
  resources :schedules
  
  
  resources :lessons do
    resources :schedules
  end
  
  resources :pterms
  resources :modes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  get 'welcome/index'
  get 'welcome/cursos'
  get 'welcome/admin'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/pterm.rb
class Pterm < ApplicationRecord
end

app/controllers/pterms_controller.rb
class PtermsController < ApplicationController
  before_action :set_pterm, only: %i[ show edit update destroy ]

  # GET /pterms or /pterms.json
  def index
    @pterms = Pterm.all
  end

  # GET /pterms/1 or /pterms/1.json
  def show
  end

  # GET /pterms/new
  def new
    @pterm = Pterm.new
  end

  # GET /pterms/1/edit
  def edit
  end

  # POST /pterms or /pterms.json
  def create
    @pterm = Pterm.new(pterm_params)

    respond_to do |format|
      if @pterm.save
        format.html { redirect_to pterm_url(@pterm), notice: "Pterm was successfully created." }
        format.json { render :show, status: :created, location: @pterm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pterms/1 or /pterms/1.json
  def update
    respond_to do |format|
      if @pterm.update(pterm_params)
        format.html { redirect_to pterm_url(@pterm), notice: "Pterm was successfully updated." }
        format.json { render :show, status: :ok, location: @pterm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pterms/1 or /pterms/1.json
  def destroy
    @pterm.destroy

    respond_to do |format|
      format.html { redirect_to pterms_url, notice: "Pterm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pterm
      @pterm = Pterm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pterm_params
      params.require(:pterm).permit(:pterm)
    end
end

app/helpers/pterms_helper.rb
module PtermsHelper
end

app/views/pterms/_form.html.erb
<%= form_with(model: pterm) do |form| %>
  <% if pterm.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pterm.errors.count, "error") %> prohibited this pterm from being saved:</h2>

      <ul>
        <% pterm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pterm, style: "display: block" %>
    <%= form.text_field :pterm %>
  </div>
 
  <br>
  <div class="btn-group">
    <%= form.submit "Guardar", class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/pterms/_pterm.html.erb
<div id="<%= dom_id pterm %>">
  <p>
    <strong>Pterm:</strong>
    <%= pterm.pterm %>
  </p>

</div>

app/views/pterms/edit.html.erb
<h1>Editing pterm</h1>

<%= render "form", pterm: @pterm %>

<br>

<div>
  <%= link_to "Show this pterm", @pterm %> |
  <%= link_to "Back to pterms", pterms_path %>
</div>

app/views/pterms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Opciones de Pago</h1>

<div class="indexcontainer">
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6">
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">ID </th>
        <th scope="col">Termino de pago</th>
        
      </tr>
      </thead>
      <tbody>
             <tr>
              <div id="lessons">
              <% @pterms.each do |pt| %>
                <tr>
                 
                <td><%= pt.id %></td>
                <td><%= pt.pterm %></td>
                <td><%= link_to "Ver este tipo de pago", @pterm, class: "btn btn-dark" %></td>
                
                
                <% end %>
              </div> 
              </tr>  
            
      </tbody>
    </table>
  </div>
</div> <br>


<div class="btn-group">
  <div>
  <%= link_to "Nuevo termino de pago", new_pterm_path, class: "btn btn-dark" %>
  
  <%= link_to "Atras", :back , class: "btn btn-dark" %>
  </div>
</div>

app/views/pterms/new.html.erb
<h1>New pterm</h1>

<%= render "form", pterm: @pterm %>

<br>



<div class="btn-group">
  <div>
  <%= link_to "Back to pterms", pterms_path, class: "btn btn-dark" %>
  
  <%= link_to "Atras", :back , class: "btn btn-dark" %>
  </div>
</div>

app/views/pterms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pterm %>

<div>
  <%= link_to "Edit this pterm", edit_pterm_path(@pterm) %> |
  <%= link_to "Back to pterms", pterms_path %>

  <%= button_to "Destroy this pterm", @pterm, method: :delete %>
</div>