config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :lessons
  resources :schedules
  
  
  resources :lessons do
    resources :schedules
  end
  
  resources :pterms
  resources :modes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  get 'welcome/index'
  get 'welcome/cursos'
  get 'welcome/admin'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :mode
  belongs_to :user
  has_many :schedules,  dependent: :destroy
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:curso, :mode_id, :user_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <% if lesson.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :curso, style: "display: block" %>
    <%= form.text_field :curso %>
  </div>

  <div>
    <%= form.label :mode_id, style: "display: block" %>
    <%= collection_select( :lesson, :mode_id, Mode.all, :id, :mode, {}, { :multiple => false } ) %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    
   
    <%= collection_select( :lesson, :user_id, User.all.where(tipo: "P"), :id, :email, {}, { :multiple => false } ) %>
    </div> <br>

  <div>
    <%= form.submit "Guardar" , class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p>
    <strong>Curso:</strong>
    <%= lesson.curso %>
  </p>

  <p>
    <strong>Mode:</strong>
    <%= lesson.mode.mode %>
  </p>

  <p>
    <strong>Profesor:</strong>
    <%= lesson.user.email %>
  </p>

  

</div>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Show this lesson", @lesson %> |
  <%= link_to "Back to lessons", lessons_path %>
</div>

app/views/lessons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cursos</h1>

<div class="indexcontainer">
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6">
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Curso</th>
        <th scope="col">Modalidad</th>
        <th scope="col">Profesor</th>
        <th scope="col">Acciones</th>
      </tr>
      </thead>
      <tbody>
             <tr>
              <div id="lessons">
              <% @lessons.each do |lesson| %>
                <tr>
                 
                <td><%= lesson.id %></td>
                <td><%= lesson.curso %></td>
                <td><%= lesson.mode.mode %></td>
                <td><%= lesson.user.email %></td>
                <td><%= link_to "Ver este curso", lesson, class: "btn btn-dark" %></td>
                 
              <% end %>
              </div> 
              </tr>  
            
      </tbody>
    </table>
  </div>
</div> <br>




<div class="btn-group">
  <div>
  <%= link_to "Nuevo curso", new_lesson_path, class: "btn btn-dark" %> 
  
  <%= link_to "Atras", :back , class: "btn btn-dark" %>
  </div>
</div>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render "form", lesson: @lesson %>

<br>

<div>
  <%= link_to "Volver a cursos", lessons_path , class: "btn btn-dark" %>
</div>

app/views/lessons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lesson %>

<div class="btn-group">
  <%= link_to "Editar este curso", edit_lesson_path(@lesson) , class: "btn btn-outline-dark" %>
  

</div> 

<div class="btn-group">
  
  <%= button_to "Eliminar este curso", @lesson, method: :delete , class: "btn btn-outline-dark"%>

</div> <br> <br> 
<div class="btn-group"> 
   <%= link_to "Volver a cursos", lessons_path , class: "btn btn-dark"%> 
</div>