config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :lessons
  resources :schedules
  
  
  resources :lessons do
    resources :schedules
  end
  
  resources :pterms
  resources :modes
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  get 'welcome/index'
  get 'welcome/cursos'
  get 'welcome/admin'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/mode.rb
class Mode < ApplicationRecord
    has_many :lessons
end

app/controllers/modes_controller.rb
class ModesController < ApplicationController
  before_action :set_mode, only: %i[ show edit update destroy ]

  # GET /modes or /modes.json
  def index
    @modes = Mode.all
  end

  # GET /modes/1 or /modes/1.json
  def show
  end

  # GET /modes/new
  def new
    @mode = Mode.new
  end

  # GET /modes/1/edit
  def edit
  end

  # POST /modes or /modes.json
  def create
    @mode = Mode.new(mode_params)

    respond_to do |format|
      if @mode.save
        format.html { redirect_to mode_url(@mode), notice: "Mode was successfully created." }
        format.json { render :show, status: :created, location: @mode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modes/1 or /modes/1.json
  def update
    respond_to do |format|
      if @mode.update(mode_params)
        format.html { redirect_to mode_url(@mode), notice: "Mode was successfully updated." }
        format.json { render :show, status: :ok, location: @mode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modes/1 or /modes/1.json
  def destroy
    @mode.destroy

    respond_to do |format|
      format.html { redirect_to modes_url, notice: "Mode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mode
      @mode = Mode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mode_params
      params.require(:mode).permit(:mode)
    end
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/views/modes/_form.html.erb
<%= form_with(model: mode) do |form| %>
  <% if mode.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mode.errors.count, "error") %> prohibited this mode from being saved:</h2>

      <ul>
        <% mode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :mode, style: "display: block" %>
    <%= form.text_field :mode %>
  </div><br>

  <div>
    <%= form.submit  "Guardar", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/modes/_mode.html.erb
<div id="<%= dom_id mode %>">
  <p>
    <strong>Mode:</strong>
    <%= mode.mode %>
  </p>

</div>

app/views/modes/edit.html.erb
<h1>Editing mode</h1>

<%= render "form", mode: @mode %>

<br>

<div>
  <%= link_to "Show this mode", @mode %> |
  <%= link_to "Back to modes", modes_path %>
</div>

app/views/modes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Modalidades</h1>
  
<div class="indexcontainer">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-6">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Modalidad</th>
          <th scope="col">Acciones</th>
        </tr>
        </thead>
        <tbody>
               <tr>
                <div id="modes">
                <% @modes.each do |mode| %>
                  <tr>
                   
                  <td><%= mode.id %></td>
                  <td><%= mode.mode %></td>
                  <td><%= link_to "Ver esta modalidad", mode, class: "btn btn-dark" %></td>
                   
                <% end %>
                </div> 
                </tr>  
              
        </tbody>
      </table>
    </div>
  </div> <br>



<div class="btn-group">
  <div>
  <%= link_to "New mode", new_mode_path ,class: "btn btn-dark"%>
  
  <%= link_to "Atras", :back , class: "btn btn-dark" %>
  </div>
</div>

app/views/modes/new.html.erb
<h1>New mode</h1>

<%= render "form", mode: @mode %>

<br>

<div>
  <%= link_to "Volver a Modalidades", modes_path , class: "btn btn-dark"%>
</div>

app/views/modes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mode %>

<div class="btn-group">
  <%= link_to "Editar esta modalidad", edit_mode_path(@mode), class: "btn btn-outline-dark" %> 
  
</div>

<div class="btn-group">

  <%= button_to "Eliminar esta modalidad", @mode, method: :delete , class: "btn btn-outline-dark"%>
</div> <br> <br>

<div class="btn-group">
  
  <%= link_to "Regresar a Modalidades", modes_path, class: "btn btn-dark" %>

</div>